language: node_js
env:
  COVERALLS_REPO_TOKEN=rCIR66aQA8jUA7Berlh1PHd917mjMt4hU #TODO: put it in private config of the repo
node_js:
  - "19"
  - "18"
  - "16"
  - "14"
after_success:
  - npm run coveralls
